### ISSUE TITLE
Monitor the prod services

### ISSUE THREAD

**Issue by TickleThePanda** [UserOfficeProject/stfc-user-office-project#104]
Split from #70. Requires #145.

We should monitor the prod services. We might be able to use UserOfficeProject/user-office-backend#81, along with Heartbeat (see isisbusapps/fba-elastic-stack#42) or Jenkins if Heartbeat isn't available.

See [`Prod_Test.Ping_MailChimpWebhooks`](https://ci.devs.facilities.rl.ac.uk/view/MailChimpWebhooks/job/Prod_Test.Ping_MailChimpWebhooks/) for a similar job.

/overwrite opened 2020-09-04

**Comment by TeraMike** [comment]
Here are the two jobs I've made, they're basically the same as the dev jobs but directed to prod instead.
[Frontend](https://ci.devs.facilities.rl.ac.uk/view/ProposalSubmission/job/Prod_Test.Ping_ProposalFrontend/) | [Backend](https://ci.devs.facilities.rl.ac.uk/view/ProposalSubmission/job/Prod_Test.Ping_ProposalBackend/)  
I haven't been able to test what happens when they build correctly but should behave just like the dev jobs.

I wasn't 100% if I've got the naming conventions there correct (I couldn't see anything else named Prod_Test) but couldn't think what else they ought to be.

**Comment by TCMeldrum** [comment]
Looks good tested the powershell scripts locally with the proxy changes and they work fine 👍

**Comment by TickleThePanda** [comment]
I agree - issue can be closed now. I will close it now. Mika, you're welcome to reopen if that's not right.

**Comment by TeraMike** [comment]
I'm not expecting any problems with the jobs from here, I'm happy to call it closed.
