### ISSUE TITLE
Fix 'Empty Button' errors ('User' role)

### ISSUE THREAD

**Issue by JEThompson97** [UserOfficeProject/stfc-user-office-project#111]
Part of #68 

> ### Empty Button error
> **What it is:** Where a button is empty or has no value text.
> **Why it maters:** When navigating to a button, descriptive text must be presented to screen reader users to indicate the function of the button.

There are several empty buttons throughout the app.
These include:

#### 1. The "Account" icon
![image](https://user-images.githubusercontent.com/31534888/117003989-73792080-acdd-11eb-8c6b-daae1e7692b1.png)

#### 2. The "close drawer" icon
![image](https://user-images.githubusercontent.com/31534888/117003960-6bb97c00-acdd-11eb-9a67-beb45ee3802f.png)

#### 3. The _disabled_ delete proposal icon
For some reason, when the `disabled` property gets set to true, the button `title` gets removed. This may require investigation.
![image](https://user-images.githubusercontent.com/31534888/117003903-580e1580-acdd-11eb-805e-7613dcf19d8a.png)

#### 4. The 4 MaterialTable navigation buttons
![image](https://user-images.githubusercontent.com/31534888/117003942-63614100-acdd-11eb-9ab7-af93cdc55f53.png)

#### 5. The "clear search" icon
![image](https://user-images.githubusercontent.com/31534888/117004095-960b3980-acdd-11eb-9c48-e3e6be1a1025.png)

_Note:_ In several of these cases, a tooltip appears when hovering over a button. Although this _implies_ there is an associated text value, **these tooltips are not assigned to the `<button>`** element itself and so do not qualify.

_Note 2:_ On a similar note to this issue, the **left-hand navigation pane icons do not display tooltip** text when hovered over like other buttons on the app. Although **this is not an official accessibility requirement**, it may have a positive general impact on UX to add tooltips here.

/overwrite opened 2020-09-04

**Comment by JEThompson97** [comment]
Sub-issues **1, 2, and 4** (documented above) are addressed by UserOfficeProject/user-office-frontend#359

Sub-issues **3 and 5** were attempted but a **solution has not yet been found.**

**Comment by JEThompson97** [comment]
After [a bit more digging](https://github.com/UserOfficeProject/stfc-user-office-project/issues/116#issuecomment-832689819), I've discovered sub-issue **3 is fine to leave as is.**
This is because when the button is disabled, it's `tabindex` becomes `-1`, making it invisible to screen readers.

**Comment by TickleThePanda** [comment]
Blocked by #116

**Comment by mr-field** [comment]
Summary for each problem reported in the original issue:
- 1: Fixed in https://github.com/UserOfficeProject/user-office-frontend/pull/359
- 2: Fixed in https://github.com/UserOfficeProject/user-office-frontend/pull/359
- 3: False positive (may be able to silence the warning with [`aria-hidden`](https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/ARIA_Techniques/Using_the_aria-hidden_attribute), but not worth doing it)
- 4: Fixed in https://github.com/UserOfficeProject/user-office-frontend/pull/359
- 5: Fixed upstream in more recent versions of Material Table. Will be fixed automatically once https://github.com/UserOfficeProject/stfc-user-office-project/issues/188 is complete

**Comment by mr-field** [comment]
The last outstanding problem was fixed by merging https://github.com/UserOfficeProject/stfc-user-office-project/issues/191.
