### ISSUE TITLE
Switch to linux containers in our local environments

### ISSUE THREAD

**Issue by ACLay** [UserOfficeProject/stfc-user-office-project#158]
Part of https://github.com/isisbusapps/docker-orchestration/issues/131

**Comment by mr-field** [comment]
It may be easier to just use Node without containers than switching to Linux, which requires setting up WSL 2. I'll schedule a DR to discuss this.

**Comment by mr-field** [comment]
The main problem is that we can't mount the code into a WSL 2 Linux container, as it would be too slow. Also, setting up WSL 2 takes quite a lot of steps. We could still run Linux containers in HyperV mode, which need no setup. Also, we can run containers that don't rely on heavy IO on mounted directories.

Without WSL 2:
- Can't run backend and frontend in Docker
- Backend and frontend must be started by `cd`ing to directory and running `npm run dev`. Could be automated with VSCode config
- Env vars must be added to `.env` files in each repo, which are not in Git
   - Can only use a single file, so sensitive stuff from BisAppSettings must be copied
- Db can still be in Docker, as well as Gateway and Scheduler backend if we want to

With WSL 2:
- Backend and frontend can run in Docker
- Can be started with `fba-compose` like we do now
- Env vars can be kept in Git through Compose files, and sensitive stuff in BisAppSettings
- Long installation
- Hacky setup
- Maybe not useful to run backend/frontend in Docker since container base is different from dev/prod

**Comment by mr-field** [comment]
Following the DR, we have decided to go for running all ESS software in WSL 2, including backend and frontend. I will prepare a guide and an install script to make the switch easier.

**Comment by mr-field** [comment]
I've pushed the changes required for this and added some instructions for the switch [on the wiki](https://github.com/isisbusapps/ISISBusApps/wiki/WSL-2). Now we a couple of people to test those instructions and confirm they work OK.

**Comment by ACLay** [comment]
Just from a read through of the instructions, do we need a "Right click on the Docker tray icon and select 'switch to linux containers'" step?

**Comment by ACLay** [comment]
Trying out these instructions, if I just run the 'for everyone' section, doing `fba-compose up bisapps-db` runs into https://github.com/isisbusapps/docker-orchestration/issues/18 again, as the settings tool build directory doesn't exist. I guess we'll need the ubuntu and linux setup script steps to be in the for everyone section too.

**Comment by ACLay** [comment]
Since the windows dev swarm is falling apart I've been trying to get proposal allocations running in linux containers. While intellij [claims to support projects in wsl2](https://www.jetbrains.com/help/idea/how-to-use-wsl-development-environment-in-product.html) I can't get it to open projects stored in WSL2 on my machine. Fortunately(?) the java apps don't do the same on the fly, IO heavy, recompilation that our node apps do. They only need to read the code files once at build time, then use a compiled jar/war that is stored within the container. So I think for those we can just work with the standard code files which get mounted into wsl at `/mnt/c/programming/...`

**Comment by mr-field** [comment]
Following Docker subscription changes, this should be done is a way that doesn't require Docker Desktop (see https://github.com/isisbusapps/ISISBusApps/issues/633). There are no Compose config changes needed for this, but Docker needs to be installed on the WSL2 distro when it's first set up. The instructions also need to be amended to avoid using Docker Desktop to install WSL2 and use our own script instead.

**Comment by mr-field** [comment]
I've now updated the instructions so that they don't require Docker Desktop anymore - in fact, they ask developers to remove it.

I've also opened 2 PRs to add the config and scripts needed for the instructions:
- https://github.com/isisbusapps/docker-orchestration/pull/153
- https://github.com/isisbusapps/ISISBusApps/pull/642

**Comment by mr-field** [comment]
The PRs have now been merged and all P&O developers have been asked to follow the [WSL2 setup instructions](https://github.com/isisbusapps/ISISBusApps/wiki/WSL-2).
