### ISSUE TITLE
Give LSF link scientists "proposal reader" role and LSF FAP secretaries "user officer" role

### ISSUE THREAD

**Issue by TickleThePanda** [UserOfficeProject/stfc-user-office-project#161]
Give LSF link scientists "proposal reader" (or "instrument scientist") roles and LSF FAP secretaries "user officer roles".

This could be all CLF staff instead of just the LSF related people.

We should remove ISIS instrument scientists from the proposal submission system instrument scientist role.

**Comment by RasmiaKulan** [comment]
Considering that the Active Directory does not have a group for CLF link scientists, there are a few ways to go about it:

1. An AD group could be created but we would never know when to update it unless we get the status automatically from the Scheduler (which isn't possible at the moment). **This could be applied as a temporary fix along with opening a new issue to improve it later on.**
2. Add people to the DB group manually by approaching each CLF facility head.
3. Asking S&O for the list of names they have as link scientists for each CLF facility to manually add them to the DB group.

**Comment by RasmiaKulan** [comment]
### Design Review Outcomes
- In terms of where to set it, we concluded the AD group would be better because it's easier to manage than the database directly i.e. the AD linked to a group/role in the database.
- Have separate AD groups per facility rather than a general CLF one for both FAP secretaries and instrument scientists.
### Possible Future Improvements
- To get some form of integration, if any of the values are changed in the Scheduler support should get notified about it.
- Better option would be if the contacts could be scraped and the list could be updated automatically.

**Comment by TickleThePanda** [comment]
Open until isisbusapps/Users#2549 is closed.

**Comment by TickleThePanda** [comment]
Closed as https://github.com/isisbusapps/Users/pull/2549 applied to prod.
