### ISSUE TITLE
Use Prod services instead of Dev services on Prod 

### ISSUE THREAD

**Issue by TCMeldrum** [UserOfficeProject/stfc-user-office-project#192]
There are a few places where the use of dev services like https://devapis.facilities.rl.ac.uk/ws/UserOfficeWebService?wsdl and https://devusers.facilities.rl.ac.uk/ are hardcoded into the backend. We should be able to configure these based on if we are on prod or dev/local as this causes issues when we make calls to the prod UOWS. This could be a form of adding the prod link as environment variables. 

Example of the error we are getting:

```Error: Request failed with status code 500
    at createError (/home/node/app/node_modules/axios/lib/core/createError.js:16:15)
    at settle (/home/node/app/node_modules/axios/lib/core/settle.js:17:12)
    at IncomingMessage.handleStreamEnd (/home/node/app/node_modules/axios/lib/adapters/http.js:260:11)
    at IncomingMessage.emit (events.js:326:22)
    at endReadableNT (_stream_readable.js:1241:12)
    at processTicksAndRejections (internal/process/task_queues.js:84:21) {
  config: {
    url: 'https://devapis.facilities.rl.ac.uk/ws/UserOfficeWebService',
    method: 'post',
    data: '<?xml version="1.0" encoding="utf-8"?><soap:Envelope xmlns:soap="http://schemas.xmlsoap.org/soap/envelope/" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"  xmlns:tns="http://webservice.UserOffice.stfc.com/"><soap:Body><tns:getRolesForUser><token>TOKEN-STRING</token><userNumber>UID</userNumber></tns:getRolesForUser></soap:Body></soap:Envelope>',
    headers: {
      Accept: 'text/html,application/xhtml+xml,application/xml,text/xml;q=0.9,*/*;q=0.8',
      'Content-Type': 'text/xml; charset=utf-8',
      'User-Agent': 'node-soap/0.40.0',
      'Accept-Encoding': 'none',
      'Accept-Charset': 'utf-8',
      Connection: 'close',
      Host: 'devapis.facilities.rl.ac.uk',
      'Content-Length': 379,
      SOAPAction: '""'
    },```

**Comment by TCMeldrum** [comment]
Copy of Cosimo's Comment on the PR so It doesn't get lost:

The UOWS client is auto-generated from the service WSDL using this command. The resulting TypeScript file is then committed to source control, so at the moment the app bundles a client for the dev UOWS. However, there may be differences between the dev and prod UOWS, such as web methods taking different arguments or returning different data. So, the dev client may not always work with the prod service.

I'm not too sure how to get around this. We could generate both clients and choose which one to use at runtime, or sync our releases with the UOWS so that there are no breaking changes. Either way, I think that should be done as a separate PR as this may be enough to solve the problem for now. Maybe we shouldn't close the parent issue yet though.

**Comment by TickleThePanda** [comment]
I'm happy that we close this and then open something for the future as a "keep an eye on this" if it becomes an issue.

I think what we have at the moment is safe for a few reasons:
1. The user's team batch up WSDL changes into a single chunk every few months (and are planning to continue to do this). A breaking change to dev will be the same for production and dev will only ever be one step ahead of production during the WSDL release process.
2. We can hotfix a WSDL change and we **should** hotfix (instead of a normal release) to decouple any release from the UOWS. This is reasonable because of the batched WSDL changes.
3. It's unlikely to matter if some areas of the UOWS API changes. The SOAP client we use will only fail if the current method being used has a different contract. We will be able to see if this fails on dev (though might rely on better). This is in comparison to our Java applications.
4. I would prefer that we don't try to switch client versions at runtime as code is simpler if it's the same in both environments.
5. The UOWS is being replaced over the next few years and, given the above reasons, any pain points won't be forever.
