### ISSUE TITLE
We need to provide a link to the new proposal system when accessing the system directly

### ISSUE THREAD

**Issue by WhittyPM** [UserOfficeProject/stfc-user-office-project#275]
The below link takes you to the initial dashboard after logging in. 

`https://proposal.isis.rl.ac.uk/home/`

There used to be a link to the new system, but for some reason this has been overwritten. Where it states "currently closed" next to LSF routes we need to update this text to a link to the new system. 

This information is also missed out of the user documentation so once completed ensure that this is reflected there as well with a screen shot if needed.

**Comment by simonfernandes** [comment]
@WhittyPM  Hi Zoe, do you have the text that should be included to the side of the button (example highlighted in the image below). And is this needed for programme access too? (the bottom button in the image).

This isn't a bug as such. It's part of our process for opening a proposal round (see [this part on the wiki](https://github.com/isisbusapps/ISISBusApps/wiki/Taking-Care-of-the-Proposal-Systems#typically-handled-by-the-user-office)). But it's good that you brought it up, because we can figure out the text in advance. Then we'll have to enable the button and apply the text at the time itself (can't be done in advance). We will need to decide who does this. It can be us as developers or the User Office, because it's something that can be done with the Data Lookup tool and a bit of familiarity (I think Emma Roberts knows how).

![image](https://user-images.githubusercontent.com/14293717/141122459-4c1fa1d1-d6bc-454f-baf1-f5c3fd44ee2a.png)

**Comment by simonfernandes** [comment]
Regarding the documentation, I guess we'll want to write this with User Officers as the audience? I can draft something.

**Comment by simonfernandes** [comment]
@TickleThePanda Can you confirm whether this upcoming round includes LSF Programme? I.e. whether we want both buttons to link off to the new site?

**Comment by TickleThePanda** [comment]
Both of those need to link to the new site.

**Comment by simonfernandes** [comment]
I've written this for documentation but I wasn't sure where to put it, so I'm posting it here for now. Do let me know if anything needs changing or if you'd like me to put this anywhere. @WhittyPM 

---

## Enabling access via the older proposal site

The older proposal site contains a page with buttons for each facility and access route. Each button is only clickable when proposals are being accepted for it. Relevant information is also typically displayed next to each button. To ensure that users who land on this page can access the new site, you will need to configure some information.

![image](https://user-images.githubusercontent.com/14293717/141336015-0744efa9-5224-4cd9-8418-918bbea0f567.png)

1. Open the [Settings Tool](https://office.facilities.rl.ac.uk/settings/).
2. Log in if you are prompted. Enter your federal ID in the 'Username' field (without the domain), and your corresponding password in the 'Password' field.
![image](https://user-images.githubusercontent.com/14293717/141336260-9b7282d4-6eca-4746-9f8c-1aceabf9ee90.png)
3. Select the 'PROP_STATUS' database by clicking on the dropdown and selecting it.
![image](https://user-images.githubusercontent.com/14293717/141336838-6d90ec63-e9c5-4740-ac24-d0c1d835f94a.png)
4. Select the 'STATUS' table by clicking on the dropdown and selecting it.
![image](https://user-images.githubusercontent.com/14293717/141337015-fb75e13d-8e9d-47cd-8e0f-f559af63e70e.png)
5. Find the relevant row in the table, by looking at the 'PROPSYSTEM' column.
![image](https://user-images.githubusercontent.com/14293717/141337832-ac7a992b-13d3-46ce-8e56-0eb33fbf150e.png)
6. Click the 'Edit' link on the far left of the desired row. A new section will appear beneath the row.
![image](https://user-images.githubusercontent.com/14293717/141338097-cef320b7-e3d4-4eb0-ac67-69b59ac1be23.png)
7. Change the 'MESSAGE' value by typing into the corresponding text box. This message will appear to the right of each button.
![image](https://user-images.githubusercontent.com/14293717/141338321-0ac7af3e-452c-4ceb-b879-ef5a801498b5.png)
8. Change the 'INTERNALSITE' value by typing either 'OPEN' or 'CLOSED' into the corresponding text box. This will make the button clickable or unclickable for STFC staff.
9. Change the 'EXTERNALSITE' value by typing either 'OPEN' or 'CLOSED' into the corresponding text box. This will make the button clickable or unclickable for non-STFC staff.

**Comment by TickleThePanda** [comment]
Closed by isisbusapps/proposal-submission#1596
