### ISSUE TITLE
Design and implement a way to authenticate a user using the STFC user office web service

### ISSUE THREAD

**Issue by TickleThePanda** [UserOfficeProject/stfc-user-office-project#44]
Refs https://github.com/UserOfficeProject/stfc-user-office-project/issues/6

Things to think about:
 - how we get the user's authentication token to the application from our dashboard
 - how do we check whether a user's token has expired
 - how we redirect when tokens expire or are invalid
 - how we do this while maintaining the existing patterns and technology that the software currently uses
 - how much of the approach do we take with the authorisation and user details

This will need a design review.

**Comment by bolmsten** [comment]
I had a discussion with @jekabs-karklins regarding this problem and our initial ideas would be to create a user entry in the user office table "users"  every time  someone new logs in, this entry would only need to contain the unique id of the user from AD. This would mean that we would not need to break all database foreign key dependencies and other logic in the mutation and query layer. 

We would also need to create a way for you to bypass database calls when getting user information as in your case this would mean a call to your user web service. We think this complexity can be handled by sending in a userDataSource into the query and mutation layer for users. This userDataSource would in our case just point to the database functions as used today but in your case it would make calls to the external service. This solution would keep all core code the same and we would just set userDataSource to different things on build depending on if it is ESS or STFC. We currently do something similar when it comes to datasources for unit-testing, there we use mockups instead of the real database. 

Hopefully this makes some sense or else I am happy to clarify

**Comment by mr-field** [comment]
See recap and proposed solution at #48 (it was a bit too long to post here, sorry)

**Comment by mr-field** [comment]
Closed by https://github.com/UserOfficeProject/user-office-backend/pull/108 and https://github.com/UserOfficeProject/user-office-frontend/pull/139.
