### ISSUE TITLE
Get Database Services to host Postgres databases for dev and prod

### ISSUE THREAD

**Issue by TickleThePanda** [UserOfficeProject/stfc-user-office-project#75]
Define and get the Database Service team to implement:
 - what we need from the databases
   - SSL access
 - how the backups need to be done (includes resolution of data loss)

/overwrite opened 2020-09-04

**Comment by RasmiaKulan** [comment]
### **New Proposal System Spec Requirements**

hardware requirements: 2 CPUs, 8GB memory, 200GB hard disk
operating system and version: CentOS 7.5
PostgreSQL version: 11


### **Systems Configured by the Database Team**

They have configured two systems with each system having two partitions:
1. The first partition will be used to store data which has approx. 200GB of system space meaning we can store 150-160GB of data.
2. The second partition will be used for backup and has 200GB of space.
   The second system will be used:
      - As a standby system in case something goes wrong.
      - For deployment purposes. In case the database team has to run some tests for example applying security patches, they will 
        run them on this system before applying them to the actual one.
Therefore, providing us with two systems with 400GB space.

### **Backup methods in place**

1. Taking snapshots of the VM (snapshots won't be used for regular backups. They will only be used for security patching or when the proposal team makes any changes to the database and requests for a snapshot backup).

2. Full backups will be taken every hour which will include a copy of all our proposal website data into a single version. (They haven't considered incremental backups because that's used for larger databases). These backups will be done hourly during office hours and will be kept locally for seven days.

3. The new system is configured with pg admin software to import or export data through pgadmin and use pgadmin to take the backup in the form of pgdumps.

4. Kashif has requested Tape Backup which will be used in case of any major data corruption. This will back up the backup folder which will have all the dumps of the hourly backups.

 

### **Steps in place for Data Corruption**
In case of any data corruption, the database team will first take the backup from the system backup drive.
If for any reason they are unable to do that, they will take the backup from the second system they've configured.
In a worst-case scenario i.e. both of those options aren't possible, they will go for Tape Recovery


### **Historical Data**
The probability to lose historical data is low as their VMware has been running for 20 years now and they haven't come across any instance of losing historical data so far.

### **Time to restore the database**
The time taken for the restoration of the database depends on the size of the database (a few GB's take few minutes) and because the new proposal system is quite small, they can't provide us with the exact figures. Therefore, to get the exact time we need to provide them with a sample database with a sufficient amount of data for them to test the time.

### **Backups during Proposal Round**
As most of the activity on the proposal system tends to happen around the actual deadline day, the database team has agreed on increasing the backups during that period so for e.g. take a backup every 15-20 mins for those specific 48 hours.
But they would like to check the system's performance for this kind of backup before applying it. To do that, we could either use the upcoming proposal round to test the system, or we could provide the database team with a few recurring proposals and let them set the backup to see how the system performs/reacts to backups happening every 15-20 mins.

**Comment by RasmiaKulan** [comment]
### This issue has been split as follows:
### _Hosting the Postgres database for dev and prod_

- https://github.com/UserOfficeProject/stfc-user-office-project/issues/91
- https://github.com/UserOfficeProject/stfc-user-office-project/issues/90

### _Setting up the SSL encryption for dev and prod_

- https://github.com/UserOfficeProject/stfc-user-office-project/issues/93
- https://github.com/UserOfficeProject/stfc-user-office-project/issues/92

**Comment by WhittyPM** [comment]
UO key stakeholders as part of the comms plan/disaster recovery/crisis management plan. 

-Emma Gozzard
-Emma Roberts

ISIS/CLF stakeholders - Zoe to explore at oversight (could be part of DB recovery plan and wider business continuity plan) 

@TickleThePanda @RasmiaKulan
