### ISSUE TITLE
Use different DB patches for STFC DB

### ISSUE THREAD

**Issue by mr-field** [UserOfficeProject/stfc-user-office-project#95]
In the future, we may want to run a different set of DB patches on the STFC DB. This could simplify problems like anabling or disabling features or adding STFC-specific data.

**Comment by mr-field** [comment]
I think this will require a distinction between "schema" DB patches (which create the tables and possibly data strictly necessary to run the app) and "data" patches (which populate the DB with facility-specific data).

**Comment by JEThompson97** [comment]
I believe this issue may require a team discussion on how we approach it.

### Possible solutions
My current understanding is that there are **two ways** we can achieve having control over the DB's data for our use of the system:
1. (as described above) **Divide the patches** into:
  a. Patches which add **schema and essential data**
  b. Patches which just add **additional data** and any facility-specific **adjustments** (i.e. disabling features)
2. Instead of splitting the patches, adding an **additional series** of patches which **adjust the data** to better suit our facility.
i.e. a set of patches which remove unwanted data, plus all those that would be in **1b** above

### Pros/Cons to each
- Option 1
  - ❌ would involve editing the current folder of DB patches, which may be undesirable.
- Option 2
  - ❌ would require us to keep making new scripts to remove data as new scripts are added by ESS.

### Question(s) to consider
- How would the **numbering** of DB patches work if split between multiple folders (especially if the facility-specific ones _won't_ be committed to this repo)
  - e.g. would facility-specific ones start from `0500` perhaps?

**Comment by JEThompson97** [comment]
From the design review (10th May 2021), the following solution was reached:

- We will use a config file to adjust the data in the DB to be tailored to a given facility.
- When the app starts, it will read the config files and use this to determine which data should be in the DB.
- To allow developers to share config files (those relevant to the facility they belong to), ‘example’ configs may be added to the repositories (which any developer can use or ignore as they wish).

To implement this solution, the following tasks need to be done:
- Any facility-specific data which is added via existing DB patches will need to be identified.
  - This data will need to be accounted for in some way (using the Features table?)
  - The ESS team should be informed of this process
- A template config file will need to be developed. 
  - From this template, an example-STFC and example-ESS config file should be implemented and tested.

**Comment by TickleThePanda** [comment]
I'm closing this one as #336 has been merged.
